### ISSUE TITLE
Feature request: upload in parallel

### ISSUE THREAD

**Issue by sharafian** [codius/codius#39]
https://github.com/codius/codius/blob/master/src/handlers/upload.js#L83

Right now, codius uploads to one host after another using this for loop. If we did Promise.all it would go many times faster when uploading to several hosts

**Comment by theogravity** [comment]
The native `Promise.all()` won't work for this situation - it rejects on the first rejection. 

You'll want to look into one of these solutions to make it work:

https://stackoverflow.com/questions/31424561/wait-until-all-es6-promises-complete-even-rejected-promises

**Comment by traviscrist** [comment]
Implemented in the Codius CLI 3.0.0.
