### ISSUE TITLE
Feature Request - make codius accept a list of hosts to choose from

### ISSUE THREAD

**Issue by steffenmandrup** [codius/codius#45]
As my company is moving towards codius we want to initially use our hosts for launching pods.

It would be nice to have codius accept a list to choose a host from depending on availability.
That way we can nice and easily expand our trusted hosts in a list instead of making tons of different cases or wrapping it ourselves

**Comment by traviscrist** [comment]
Great idea, would codius upload to all hosts in the provided list or instead select randomly say 3 out of a list of 20 and keep trying until it had 3 successful uploads?

**Comment by steffenmandrup** [comment]
Just 1 of them :-) just wanna safe guard that if 1 server is fully occupied then it knows where to go next! However it would be just as useful when wanting to host x amount of pods! In general just specifying a list of hosts instead of 1 would be nice! Then a separate command for the amount of pods you want

**Comment by traviscrist** [comment]
Added support for this in the Codius CLI 3.0.0 which accepts a `codiushosts.json` file to support using your own list of hosts. See the Codius README https://github.com/codius/codius for more details.
