### ISSUE TITLE
You gave up?

### ISSUE THREAD

**Issue by lazaridiscom** [codius/codius#77]
-

**Comment by adrianhopebailie** [comment]
https://coil.com/p/wilsonianb/Codius-Host-2-0-Preview/xj-5cIC4u

**Comment by lazaridiscom** [comment]
Officially, what's going on with the root project here?

**Comment by wilsonianb** [comment]
@lazaridiscom This is still the official project/repo.
Changes are submitted here via pull requests when they're ready for review.

**Comment by lazaridiscom** [comment]
Super unprofessional impression...
